//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tpircsavajlexipigeliamemorymmousenilcrabksatxinuyhstfgdndirectoryetaoeoopowersupplynirfrloucoasaevasscretndgkiropktypshruwweelcddecpreeahycaatrmanrimalltdrperreatbolenmeieketseephhrckiprafcvriirsulmeebeiarriabootmbornstwraprgrtnwbingonoosgndloodintioisangmakaularaoteanrcaeasptltaiponrndusnfirewallwreikooctfdprdhtooteulbyte.
        /// </summary>
        public static string ComputersLetters {
            get {
                return ResourceManager.GetString("ComputersLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string ComputersWidth {
            get {
                return ResourceManager.GetString("ComputersWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application;backup;binary;bluetooth;boot;byte;chat;click;cookie;cursor;data;defragment;directory;disk;drive;dos;drag;email;encryption;file;firewall;folder;gif;google;html;icon;internet;javascript;kernal;lcd;login;memory;monitor;mouse;nanosecond;network;partition;paste;pdf;pixel;power;supply;programmer;router;save;scanner;security;shareware;software;spam;taskbar;thumbnail;unix;wallpaper;wireless.
        /// </summary>
        public static string ComputersWords {
            get {
                return ResourceManager.GetString("ComputersWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catoaawar.
        /// </summary>
        public static string SimpleLetters {
            get {
                return ResourceManager.GetString("SimpleLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string SimpleWidth {
            get {
                return ResourceManager.GetString("SimpleWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cat;war;car;rat.
        /// </summary>
        public static string SimpleWords {
            get {
                return ResourceManager.GetString("SimpleWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibnuvgwyuhgstgcsmokedgarlichpqrfbalsyokxpcgqacrdfetabdymliqqynfypiqledznwteoruthvsdlmuutrmxwnsaiuseibonaruwjtnkweeducecechzltcftrvimltpyruotmraflowoolvampiretrtrlsrcchutneyabyogcbksdppiegdqtnifllqhysecbsuiuapuedasmtquxxhssabn.
        /// </summary>
        public static string TestLetters {
            get {
                return ResourceManager.GetString("TestLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string TestWidth {
            get {
                return ResourceManager.GetString("TestWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TestWords {
            get {
                return ResourceManager.GetString("TestWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wverticallrooafflsabacriliatoandodkonwdcdrkesooddkoeepzegliwmsiihoaeraalrkrrirerkodidedrcdhelwsleuth.
        /// </summary>
        public static string WikipediaLetters {
            get {
                return ResourceManager.GetString("WikipediaLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string WikipediaWidth {
            get {
                return ResourceManager.GetString("WikipediaWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find;Random;Sleuth;Backward;Vertical;Diagonal;Horizontal;Word;Search.
        /// </summary>
        public static string WikipediaWords {
            get {
                return ResourceManager.GetString("WikipediaWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\wordsEn.txt.
        /// </summary>
        public static string WordListFilename {
            get {
                return ResourceManager.GetString("WordListFilename", resourceCulture);
            }
        }
    }
}
